### ISSUE TITLE
Bot kennt Syntax nicht

### ISSUE THREAD

**Issue by tabacha** [tabacha/WoIstDerWagen#9]
# IC144 Hannover Wagen 11

@woistderwagen #ic2073 berlin wagen 5

**Comment by tabacha** [comment]
orless   @WoIstDerWagen #ICE1557 Fulda Wagen 27
msg="#ICE1557 Fulda Wagen 27"
1:ICE 1557      2:Fulda
get https://open-api.bahn.de/bin/rest.exe/location.name?authKey=DBhackFrankfurt0316&lang=de&input=Fulda&format=json
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    txt='@' + mention.author.screen_name + ' ' + msgParse.answer(question, cnx)
  File "/home/sven/git/WoIstDerWagen/pythonBot/msgParse.py", line 48, in answer
    rtn=live_api.getLiveData(zugArt+' '+zugNr, bahnhof)
  File "/home/sven/git/WoIstDerWagen/pythonBot/live_api.py", line 22, in getLiveData
    station_id=stations['LocationList']['StopLocation'][0]['id']
KeyError: 0

**Comment by tabacha** [comment]
Die Anfrage geht jetzt, und auch der Fehler mit der ID von Ulm ist gefixt.
